apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }} # sample-app-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.deployment.lables.app }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
